import type { Metadata } from "next";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { AppHeader } from "@/components/app-header";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { AuthInitializer } from "@/features/auth/components/AuthInitializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children 
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
        <AuthInitializer/>
        <AppSidebar variant="inset"/>
        <SidebarInset>
            <AppHeader/>
            <main className="flex flex-1 flex-col gap-4 p-4 pt-0">
                {children} 
            </main>
        </SidebarInset>
    </SidebarProvider>
  );
}
