import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body> 
                <Provider>
                    <div className="flex flex-1 flex-col min-h-full">
                        {children}
                    </div>
                </Provider>
            </body>
        </html>
    );
}