import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import { Toaster } from "@/components/ui/sonner";
import Provider from "./provider";
import ReduxProvider from "@/store/redux-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="light"> 
                <ReduxProvider>
                    <Provider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <div className="flex flex-1 flex-col min-h-full">
                                {children}
                            </div>
                            <Toaster position="top-center" />
                        </ThemeProvider>
                    </Provider>
                </ReduxProvider>
            </body>
        </html>
    );
}