import type { Metadata } from "next";
import "../globals.css";

import DashboardLayout from "../../components/dashboard-layout/DashboardLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ 
    children 
}: {
    children: React.ReactNode;
}) {
    return (
        <DashboardLayout>
            {children} 
        </DashboardLayout>
    );
}
