import type { Metadata } from "next";
import "../globals.css";
import { AppSidebar } from "@/components/AppSidebar";
import { AppHeader } from "@/components/AppHeader";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { AuthInitializer } from "@/features/auth/components/AuthInitializer";
import AuthProvider from "@/features/auth/components/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children 
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
        <AuthInitializer/>
        <AppSidebar variant="inset" className="px-1"/>
        <SidebarInset>
            <AppHeader/>
            <AuthProvider>
                <main className="flex flex-1 flex-col gap-4 p-4 pt-0">
                    {children} 
                </main>
            </AuthProvider>
        </SidebarInset>
    </SidebarProvider>
  );
}
